from .usuarioSerializer import UsuarioSerializer
from .pacienteSerializer import PacienteSerializer
from .psaludSerializer import PersonalSaludSerializer
from .familiarSerializer import FamiliarSerializer
from .historiaSerializer import HistoriaSerializer
from .sigvitalesSerializer import SignosVitalesSerializers