# Generated by Django 4.1.1 on 2022-10-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('fNacimiento', models.DateField(verbose_name='FechaNacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('perfil', models.CharField(max_length=30, verbose_name='Rol')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigVitales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=30, verbose_name='Oximetria')),
                ('fRespiratiria', models.CharField(max_length=30, verbose_name='FreRespiratoria')),
                ('fCardiaca', models.CharField(max_length=30, verbose_name='FreCardiaca')),
                ('temperatura', models.CharField(max_length=30, verbose_name='Temperatura')),
                ('glicemias', models.CharField(max_length=30, verbose_name='Glicemias')),
                ('pArterial', models.CharField(max_length=30, verbose_name='PreArterial')),
                ('fechaHora', models.DateTimeField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigVitales', to='HospitalHomeBE.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(max_length=30, verbose_name='Rol')),
                ('especialidad', models.CharField(max_length=30, verbose_name='Especialidad')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pSalud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='perSalud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='HospitalHomeBE.personalsalud'),
        ),
        migrations.CreateModel(
            name='HisClinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sugCuidado', models.CharField(max_length=500, verbose_name='SugCuidado')),
                ('diagnostico', models.CharField(max_length=100, verbose_name='Diagnostico')),
                ('entorno', models.CharField(max_length=100, verbose_name='Entorno')),
                ('fSugerencia', models.DateField()),
                ('descripcion', models.CharField(max_length=800, verbose_name='Descripcion')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hClinica', to='HospitalHomeBE.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=40, verbose_name='Parentesco')),
                ('correo', models.EmailField(max_length=100, verbose_name='correo')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='HospitalHomeBE.paciente')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
