# Generated by Django 4.1.1 on 2022-10-05 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('perfil', models.CharField(max_length=30, verbose_name='Perfil')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=30, verbose_name='Dirección')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signos_vitales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=30, verbose_name='SugerenciasOximetria')),
                ('frecuenciaRespiratoria', models.CharField(max_length=30, verbose_name='Frecuencia_respiratoria')),
                ('frecuenciaCardiaca', models.CharField(max_length=30, verbose_name='Frecuencia_cardiaca')),
                ('temperatura', models.CharField(max_length=30, verbose_name='Temperatura')),
                ('glicemias', models.CharField(max_length=150, verbose_name='Glicemias')),
                ('presionArterial', models.CharField(max_length=30, verbose_name='Presion_arterial')),
                ('fechaHora', models.DateTimeField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigvitales', to='HospitalHomeBE.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_salud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=30, verbose_name='Rol')),
                ('especialidad', models.CharField(max_length=30, verbose_name='Especialidad')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Psalud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_psalud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='HospitalHomeBE.personal_salud'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sugerencias', models.CharField(max_length=300, verbose_name='Sugerencias')),
                ('diagnostico', models.CharField(max_length=300, verbose_name='Diagnostico')),
                ('entorno', models.CharField(max_length=300, verbose_name='Entorno')),
                ('fecha_sugerencia', models.DateField()),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histclinica', to='HospitalHomeBE.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=30, verbose_name='Parentesco')),
                ('correo', models.EmailField(max_length=80, verbose_name='Correo')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
