# Generated by Django 4.1.1 on 2022-09-27 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalHomeBE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='registro',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalHomeBE.medico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Contraseña'),
        ),
    ]
